name: CMake on a single platform (x86)

on:
  push:
    branches: [ "CMake-Alpha-ASTP" ]

env:
  GH_TOKEN: ${{github.token}}
  BUILD_TYPE: RelWithDebInfo
  BUILD_NAME: NASSP-V9.0-Alpha-VHF-${{github.run_number}}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Check dependency cache for Orbiter 2024 x86
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{github.workspace}}/Orbiter2024-x86.zip
        key: O2024-x86-zip
    
    - name: Download Orbiter 2024 x86 if not cached
      if: steps.cache.outputs.cache-hit != 'true'
      run: Invoke-WebRequest -Uri https://github.com/orbitersim/orbiter/releases/download/2024/Orbiter-x86.zip -OutFile ${{github.workspace}}/Orbiter2024-x86.zip
    
    - name: Extract Orbiter
      run: Expand-Archive -Force ${{github.workspace}}/Orbiter2024-x86.zip ${{github.workspace}}/Orbiter2024

    - name: Configure CMake
      run: >
        cmake
        -DORBITER_INSTALL_DIR:STRING="${{github.workspace}}/Orbiter2024"
        -DFINAL_INSTALL_DIR:STRING="${{github.workspace}}/install"
        -B ${{github.workspace}}/build
        -G "Visual Studio 17 2022"
        -A Win32
        ${{github.workspace}}/Orbitersdk/samples/ProjectApollo/

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4
      
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Write version file
      run: |
        $version = "${{ env.BUILD_NAME }}"
        @"
        $version
        "@ | Out-File -Encoding UTF8 "${{ github.workspace }}/install/NASSP_VERSION.txt"

    - name: Zip output directory
      run: Compress-Archive -Path ${{github.workspace}}/install/* -DestinationPath ${{github.workspace}}/${{env.BUILD_NAME}}-x86.zip -Force
      
    - name: Create GitHub release and tag
      run: gh release create ${{env.BUILD_NAME}} ${{github.workspace}}/${{env.BUILD_NAME}}-x86.zip --target CMake

    - name: Create QSG asset
      run: gh release upload ${{env.BUILD_NAME}} '${{github.workspace}}/Doc/Project Apollo - NASSP/NASSP Quick Start Guide.pdf'
      
    - name: Create Autosave asset
      run: gh release upload ${{env.BUILD_NAME}} '${{github.workspace}}/Doc/Project Apollo - NASSP/Autosave.txt'